#!/usr/bin/env python3
"""Batch-upgrade lecture HTML with the latest md2html-lecture template.

For each converter-generated .html (footer "Generated by md2html") that has a
sibling .md — whatever the filename suffix (_整理文档, _项目式学习, …):
  1. Extract hand-added Mermaid <figure class="diagram"> blocks (keyed by preceding h2)
  2. Re-run build_html.py
  3. Re-inject diagrams + generic speaker tags + light bio italic fix
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

DEFAULT_BUILD = Path(__file__).resolve().with_name("build_html.py")
DEFAULT_GLOB = "*.html"
GENERATED_MARKER = "Generated by md2html"

H2_RE = re.compile(r'<h2\s+id="([^"]+)"[^>]*>.*?</h2>', re.DOTALL | re.IGNORECASE)
BIO_ITALIC_RE = re.compile(r"(?<![</\w])\*([^*\n]{2,80})\*(?!\*)")


FIGURE_RE = re.compile(r'<figure\s+class="diagram">.*?</figure>', re.DOTALL | re.IGNORECASE)


def _section_end(html: str, start: int) -> int:
    nxt = re.search(r"<h2[\s>]|<!-- CONTENT_END -->", html[start:], re.IGNORECASE)
    return start + nxt.start() if nxt else len(html)


def extract_diagrams(html: str) -> dict[str, list[str]]:
    """Map h2 id -> every diagram inside that section (after the h2 or the insight)."""
    found: dict[str, list[str]] = {}
    for m in H2_RE.finditer(html):
        section = html[m.end() : _section_end(html, m.end())]
        figs = [f.strip() for f in FIGURE_RE.findall(section)]
        if figs and m.group(1) not in found:
            found[m.group(1)] = figs
    return found


def count_figures(diagrams: dict[str, list[str] | str]) -> int:
    """Total diagrams across all sections (values may be one figure or a list)."""
    return sum(1 if isinstance(v, str) else len(v) for v in diagrams.values())


def inject_diagrams(html: str, diagrams: dict[str, list[str] | str]) -> tuple[int, str]:
    """Re-insert saved diagrams after each section's 核心洞察 callout (or its h2
    when the section has no insight). Returns (added, html)."""
    added = 0
    for hid, figs in diagrams.items():
        if isinstance(figs, str):
            figs = [figs]
        pat = re.compile(
            rf'(<h2\s+id="{re.escape(hid)}"[^>]*>.*?</h2>)\s*',
            re.DOTALL | re.IGNORECASE,
        )
        m = pat.search(html)
        if not m:
            continue
        end = _section_end(html, m.end())
        section = html[m.end() : end]
        if 'class="diagram"' in section:
            continue
        start = m.end()
        im = re.compile(
            rf'<h3\s+id="{re.escape(hid)}-insight"[^>]*>.*?</h3>\s*'
            r'<div class="callout callout-tip section-insight">.*?</div>\s*</div>\s*',
            re.DOTALL,
        ).search(section)
        if im:
            start = m.end() + im.end()
        html = html[:start] + "\n\n".join(figs) + "\n\n" + html[start:]
        added += len(figs)
    return added, html


def patch_speakers(html: str) -> str:
    """Upgrade legacy per-file speaker hardcodes to the template's generic version."""
    old = """    function tagSpeakers() {
      document.querySelectorAll(".timeline .step-body h3").forEach(h3 => {
        const step = h3.closest(".step");
        if (!step) return;
        const name = h3.textContent.trim();
        if (/Harrison/i.test(name)) step.classList.add("speaker-host");
        else if (/Andrew/i.test(name)) step.classList.add("speaker-guest");
      });
    }"""
    new = """    function tagSpeakers() {
      // First two distinct speakers in reading order = host, then guest.
      const names = [];
      document.querySelectorAll(".timeline .step-body h3").forEach(h3 => {
        const n = h3.textContent.trim();
        if (n && !names.includes(n)) names.push(n);
      });
      const host = names[0] || "";
      const guest = names[1] || "";
      document.querySelectorAll(".timeline .step-body h3").forEach(h3 => {
        const step = h3.closest(".step");
        if (!step) return;
        const name = h3.textContent.trim();
        if (host && name === host) step.classList.add("speaker-host");
        else if (guest && name === guest) step.classList.add("speaker-guest");
      });
    }"""
    # Also match already-patched Patrick/Sam version
    alt_old = """    function tagSpeakers() {
      document.querySelectorAll(".timeline .step-body h3").forEach(h3 => {
        const step = h3.closest(".step");
        if (!step) return;
        const name = h3.textContent.trim();
        if (/Patrick/i.test(name)) step.classList.add("speaker-host");
        else if (/Sam Altman|Altman/i.test(name)) step.classList.add("speaker-guest");
      });
    }"""
    if old in html:
        return html.replace(old, new, 1)
    if alt_old in html:
        return html.replace(alt_old, new, 1)
    if "function tagSpeakers()" in html and "names.includes" not in html:
        # Fallback: regex replace the whole function body
        return re.sub(
            r"    function tagSpeakers\(\) \{.*?\n    \}",
            new,
            html,
            count=1,
            flags=re.DOTALL,
        )
    return html


def fix_bio_italics(html: str) -> str:
    """Convert leftover *markdown italics* inside speaker-bio to <em>."""
    def repl_bio(m: re.Match) -> str:
        block = m.group(0)
        block2 = BIO_ITALIC_RE.sub(r"<em>\1</em>", block)
        return block2

    return re.sub(
        r'(<aside class="callout callout-info speaker-bio"[^>]*>.*?</aside>)',
        repl_bio,
        html,
        count=1,
        flags=re.DOTALL,
    )


def shorten_meta_if_long(html: str) -> str:
    """If meta source line is very long, keep text after last ' · ' segment pair lightly trimmed.
    Only touch lines that look like full English titles with duplicate names."""
    # Soften: leave as-is unless > 120 chars — prefer Invest/Lenny-style short form already handled per-file.
    return html


def is_generated(html_path: Path) -> bool:
    """Only lecture pages built by build_html.py (skips 公众号 HTML and others)."""
    try:
        return GENERATED_MARKER in html_path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False


def process_one(md: Path, root: Path, build: Path) -> dict:
    html_path = md.with_suffix(".html")
    result = {
        "md": str(md.relative_to(root)),
        "ok": False,
        "diagrams_saved": 0,
        "diagrams_restored": 0,
        "error": "",
    }
    if not html_path.exists():
        result["error"] = "no-html"
        return result

    old_html = html_path.read_text(encoding="utf-8")
    diagrams = extract_diagrams(old_html)
    result["diagrams_saved"] = count_figures(diagrams)

    proc = subprocess.run(
        [sys.executable, str(build), str(md), str(html_path)],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    if proc.returncode != 0:
        result["error"] = (proc.stderr or proc.stdout or "build failed")[:300]
        return result

    new_html = html_path.read_text(encoding="utf-8")
    restored, new_html = inject_diagrams(new_html, diagrams)
    result["diagrams_restored"] = restored
    new_html = patch_speakers(new_html)
    new_html = fix_bio_italics(new_html)
    new_html = shorten_meta_if_long(new_html)
    html_path.write_text(new_html, encoding="utf-8")
    result["ok"] = True
    if "Wrote" in (proc.stdout or ""):
        # capture sections line
        for line in (proc.stdout or "").splitlines():
            if "sections=" in line or "Wrote" in line:
                result["build"] = line.strip()
    return result


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Re-build lecture HTML in place, preserving hand-added Mermaid diagrams."
    )
    parser.add_argument("root", type=Path, help="directory scanned recursively for lecture HTML")
    parser.add_argument(
        "--build",
        type=Path,
        default=DEFAULT_BUILD,
        help="path to build_html.py (default: alongside this script)",
    )
    parser.add_argument(
        "--glob",
        default=DEFAULT_GLOB,
        help=f"HTML filename pattern to upgrade (default: {DEFAULT_GLOB})",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    # Note titles and progress arrows can fall outside a legacy console codepage
    # (cp936 has no U+2194); degrade those characters instead of aborting.
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(errors="replace")

    args = parse_args(argv)
    root = args.root.expanduser().resolve()
    build = args.build.expanduser().resolve()
    if not root.is_dir():
        print(f"error: root is not a directory: {root}", file=sys.stderr)
        return 2
    if not build.is_file():
        print(f"error: build script not found: {build}", file=sys.stderr)
        return 2

    targets = []
    for h in sorted(root.rglob(args.glob)):
        md = h.with_suffix(".md")
        if md.exists() and is_generated(h):
            targets.append(md)

    print(f"Found {len(targets)} HTML↔MD pairs under {root}")
    ok = fail = 0
    total_restored = 0
    for i, md in enumerate(targets, 1):
        r = process_one(md, root, build)
        status = "OK" if r["ok"] else "FAIL"
        if r["ok"]:
            ok += 1
            total_restored += r["diagrams_restored"]
        else:
            fail += 1
        extra = r.get("build", r.get("error", ""))
        print(
            f"[{i}/{len(targets)}] {status} "
            f"diag {r['diagrams_saved']}→{r['diagrams_restored']}  "
            f"{r['md']}"
            + (f"  | {extra}" if extra else "")
        )

    print(f"\nDone: ok={ok} fail={fail} diagrams_restored={total_restored}")
    return 0 if fail == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
