#!/usr/bin/env python3
"""Batch-upgrade lecture HTML with the latest md2html-lecture template.

For each converter-generated .html (footer "Generated by md2html") that has a
sibling .md — whatever the filename suffix (_整理文档, _项目式学习, …):
  1. Extract hand-added Mermaid <figure class="diagram"> blocks (keyed by preceding h2)
  2. Re-run build_html.py into a temporary file in the same directory
  3. Restore diagrams and header edits, validate, then atomically replace HTML
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from html.parser import HTMLParser
from pathlib import Path

DEFAULT_BUILD = Path(__file__).resolve().with_name("build_html.py")
DEFAULT_GLOB = "*.html"
GENERATED_MARKER = "Generated by md2html"

H2_RE = re.compile(r'<h2\s+id="([^"]+)"[^>]*>.*?</h2>', re.DOTALL | re.IGNORECASE)


FIGURE_RE = re.compile(
    r'''<figure\b(?=[^>]*\bclass=["'](?:[^"']*\s)?diagram(?:\s[^"']*)?["'])[^>]*>.*?</figure>''',
    re.DOTALL | re.IGNORECASE,
)


def header_patterns():
    """Allowlisted header contents; reading time and source footer stay derived."""
    patterns = {"title": r"(<title\b[^>]*>)(.*?)(</title>)"}
    for key, tag in (("doc-title", "h1"), ("doc-eyebrow", "span"), ("doc-subtitle", "p")):
        patterns[key] = (
            rf'''(<{tag}\b[^>]*\bclass=["'](?:[^"']*\s)?{key}(?:\s[^"']*)?["'][^>]*>)'''
            rf"(.*?)(</{tag}>)"
        )
    for key, icon in (("meta-source", "i-file"), ("meta-date", "i-calendar")):
        patterns[key] = rf'''(<use\b[^>]*\bhref=["']\#{icon}["'][^>]*/>\s*</svg>\s*)(.*?)(</span>)'''
    return {k: re.compile(v, re.DOTALL | re.IGNORECASE) for k, v in patterns.items()}


HEADER_PATTERNS = header_patterns()
HEADER_DEFAULTS_RE = re.compile(
    r'<script\b[^>]*\bid="lecture-header-defaults"[^>]*>(.*?)</script>', re.DOTALL
)


def header_overrides(old_html: str) -> dict[str, str]:
    """Detect edits against recorded defaults; legacy pages keep their header."""
    match = HEADER_DEFAULTS_RE.search(old_html)
    defaults = {}
    if match:
        defaults = json.loads(match.group(1))
        if not isinstance(defaults, dict) or any(not isinstance(v, str) for v in defaults.values()):
            raise ValueError("invalid header defaults snapshot")
    overrides = {}
    for key, pattern in HEADER_PATTERNS.items():
        field = pattern.search(old_html)
        if field:
            value = field.group(2).strip()
            if key not in defaults or value != defaults[key]:
                overrides[key] = value
    return overrides


def restore_header(html: str, overrides: dict[str, str]) -> str:
    for key, value in overrides.items():
        html, count = HEADER_PATTERNS[key].subn(
            lambda m: m.group(1) + value + m.group(3), html, count=1
        )
        if count != 1:
            raise ValueError("cannot preserve header field: %s" % key)
    return html


class PageStructure(HTMLParser):
    def __init__(self):
        super().__init__()
        self.ids, self.duplicates, self.links = set(), set(), []
        self.sections = 0
        self.in_toc = False

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        sid = attrs.get("id")
        if sid is not None:
            if sid in self.ids:
                self.duplicates.add(sid)
            self.ids.add(sid)
        if tag == "h2" and "sec" in (attrs.get("class") or "").split():
            self.sections += 1
        if tag == "nav" and sid == "toc-nav":
            self.in_toc = True
        if tag == "a" and self.in_toc and (attrs.get("href") or "").startswith("#"):
            if attrs["href"] != "#":
                self.links.append(attrs["href"][1:])

    def handle_endtag(self, tag):
        if tag == "nav":
            self.in_toc = False


def validate_page(html: str, expected_sections: int) -> None:
    if not all(marker in html for marker in (GENERATED_MARKER, "<!-- CONTENT_START -->", "<!-- CONTENT_END -->")):
        raise ValueError("converter output is not a complete lecture page")
    page = PageStructure()
    page.feed(html)
    if page.duplicates:
        raise ValueError("duplicate HTML ids: %s" % ", ".join(sorted(page.duplicates)))
    if page.sections != expected_sections:
        raise ValueError("section count mismatch: %d != %d" % (page.sections, expected_sections))
    missing = set(page.links) - page.ids
    if missing:
        raise ValueError("missing anchor targets: %s" % ", ".join(sorted(missing)))


def _section_end(html: str, start: int) -> int:
    nxt = re.search(r"<h2[\s>]|<!-- CONTENT_END -->", html[start:], re.IGNORECASE)
    return start + nxt.start() if nxt else len(html)


def extract_diagrams(html: str) -> dict[str, list[str]]:
    """Map h2 id -> every diagram inside that section (after the h2 or the insight)."""
    found: dict[str, list[str]] = {}
    for m in H2_RE.finditer(html):
        section = html[m.end() : _section_end(html, m.end())]
        figs = [f.strip() for f in FIGURE_RE.findall(section)]
        if figs and m.group(1) not in found:
            found[m.group(1)] = figs
    return found


def count_figures(diagrams: dict[str, list[str] | str]) -> int:
    """Total diagrams across all sections (values may be one figure or a list)."""
    return sum(1 if isinstance(v, str) else len(v) for v in diagrams.values())


def inject_diagrams(html: str, diagrams: dict[str, list[str] | str]) -> tuple[int, str]:
    """Re-insert saved diagrams after each section's 核心洞察 callout (or its h2
    when the section has no insight). Returns (added, html)."""
    added = 0
    for hid, figs in diagrams.items():
        if isinstance(figs, str):
            figs = [figs]
        pat = re.compile(
            rf'(<h2\s+id="{re.escape(hid)}"[^>]*>.*?</h2>)\s*',
            re.DOTALL | re.IGNORECASE,
        )
        m = pat.search(html)
        if not m:
            continue
        end = _section_end(html, m.end())
        section = html[m.end() : end]
        if FIGURE_RE.search(section):
            continue
        start = m.end()
        im = re.compile(
            r'<h3\b[^>]*class="layer-heading layer-insight"[^>]*>.*?</h3>\s*'
            r'<div class="callout callout-tip section-insight">.*?</div>\s*</div>\s*',
            re.DOTALL,
        ).search(section)
        if im:
            start = m.end() + im.end()
        html = html[:start] + "\n\n".join(figs) + "\n\n" + html[start:]
        added += len(figs)
    return added, html


def is_generated(html_path: Path) -> bool:
    """Only lecture pages built by build_html.py (skips 公众号 HTML and others)."""
    try:
        return GENERATED_MARKER in html_path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False


def process_one(md: Path, root: Path, build: Path, refresh_header: bool = False) -> dict:
    html_path = md.with_suffix(".html")
    result = {
        "md": str(md.relative_to(root)),
        "ok": False,
        "diagrams_saved": 0,
        "diagrams_restored": 0,
        "header_preserved": 0,
        "warnings": [],
        "error": "",
    }
    if not html_path.exists():
        result["error"] = "no-html"
        return result

    temporary = None
    try:
        old_bytes = html_path.read_bytes()
        old_html = old_bytes.decode("utf-8").replace("\r\n", "\n").replace("\r", "\n")
        source_bytes = md.read_bytes()
        diagrams = extract_diagrams(old_html)
        result["diagrams_saved"] = len(FIGURE_RE.findall(old_html))
        section_ids = [m.group(1) for m in H2_RE.finditer(old_html)]
        if result["diagrams_saved"] and len(section_ids) != len(set(section_ids)):
            raise ValueError("ambiguous section ids for saved diagrams; old HTML kept")
        if count_figures(diagrams) != result["diagrams_saved"]:
            raise ValueError("unassigned diagrams or ambiguous section ids; old HTML kept")
        overrides = {} if refresh_header else header_overrides(old_html)

        fd, filename = tempfile.mkstemp(prefix=".lecture-upgrade-", suffix=".html", dir=html_path.parent)
        os.close(fd)
        temporary = Path(filename)
        proc = subprocess.run(
            [sys.executable, "-X", "utf8", str(build), str(md), str(temporary)],
            capture_output=True, text=True, encoding="utf-8", errors="replace",
        )
        output = (proc.stdout or "") + "\n" + (proc.stderr or "")
        result["warnings"] = [line.strip() for line in output.splitlines() if line.strip().startswith("WARN:")]
        for line in (proc.stdout or "").splitlines():
            if "sections=" in line:
                result["build"] = line.strip()
        if proc.returncode != 0:
            result["error"] = (proc.stderr or proc.stdout or "build failed")[-500:].strip()
            return result
        if result["warnings"]:
            result["error"] = "source warnings require review; old HTML kept"
            return result

        counts = re.search(r"\bsections=(\d+)", proc.stdout or "")
        if not counts:
            raise ValueError("converter did not report a section count; old HTML kept")
        new_html = temporary.read_text(encoding="utf-8")
        restored, new_html = inject_diagrams(new_html, diagrams)
        result["diagrams_restored"] = restored
        if restored != result["diagrams_saved"]:
            raise ValueError("diagram restoration incomplete: %d/%d; old HTML kept" % (restored, result["diagrams_saved"]))
        new_html = restore_header(new_html, overrides)
        result["header_preserved"] = len(overrides)
        validate_page(new_html, int(counts.group(1)))
        temporary.write_text(new_html, encoding="utf-8")
        if html_path.read_bytes() != old_bytes or md.read_bytes() != source_bytes:
            raise ValueError("source or HTML changed during conversion; replacement cancelled")
        os.replace(temporary, html_path)
        result["ok"] = True
    except (OSError, UnicodeError, ValueError) as exc:
        result["error"] = str(exc)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
    return result


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Re-build lecture HTML in place, preserving hand-added Mermaid diagrams."
    )
    parser.add_argument("root", type=Path, help="directory scanned recursively for lecture HTML")
    parser.add_argument(
        "--build",
        type=Path,
        default=DEFAULT_BUILD,
        help="path to build_html.py (default: alongside this script)",
    )
    parser.add_argument(
        "--glob",
        default=DEFAULT_GLOB,
        help=f"HTML filename pattern to upgrade (default: {DEFAULT_GLOB})",
    )
    parser.add_argument(
        "--refresh-header", action="store_true",
        help="re-derive all header fields from Markdown instead of preserving manual edits",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    # Note titles and progress arrows can fall outside a legacy console codepage
    # (cp936 has no U+2194); degrade those characters instead of aborting.
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(errors="replace")

    args = parse_args(argv)
    root = args.root.expanduser().resolve()
    build = args.build.expanduser().resolve()
    if not root.is_dir():
        print(f"error: root is not a directory: {root}", file=sys.stderr)
        return 2
    if not build.is_file():
        print(f"error: build script not found: {build}", file=sys.stderr)
        return 2

    targets = []
    for h in sorted(root.rglob(args.glob)):
        md = h.with_suffix(".md")
        if md.exists() and is_generated(h):
            targets.append(md)

    print(f"Found {len(targets)} HTML↔MD pairs under {root}")
    ok = fail = 0
    total_restored = 0
    for i, md in enumerate(targets, 1):
        r = process_one(md, root, build, refresh_header=args.refresh_header)
        status = "OK" if r["ok"] else "FAIL"
        if r["ok"]:
            ok += 1
            total_restored += r["diagrams_restored"]
        else:
            fail += 1
        extra = r.get("build", "") if r["ok"] else r["error"]
        print(
            f"[{i}/{len(targets)}] {status} "
            f"diag {r['diagrams_saved']}→{r['diagrams_restored']}  "
            f"{r['md']}"
            + (f"  | {extra}" if extra else "")
        )
        for warning in r["warnings"]:
            print("  " + warning)

    print(f"\nDone: ok={ok} fail={fail} diagrams_restored={total_restored}")
    return 0 if fail == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
